### ISSUE TITLE
ros_graph

### ISSUE THREAD

**Issue by 2amour** [RozDavid/loam-segmatch#2]
Hi,@RozDavid , could you show me your ros_graph of the laom-segmatch?Thank you!

**Comment by RozDavid** [comment]
Hi @2amour,

So the purpose of this modification of the loam project is to work in the original ROS (x forward, z up conevntion) so that I could use a localization step with loam, in my case segmap/segmatch.

For your question this is the output graph for the merged projects. Good luck for you!

![image](https://user-images.githubusercontent.com/23144199/46437729-53b3a180-c75c-11e8-95b5-deb89e39dd0c.png)

**Comment by 2amour** [comment]
Thank you @RozDavid
